import { pgTable, text, integer, doublePrecision, boolean, timestamp, jsonb, serial } from 'drizzle-orm/pg-core';

export const users = pgTable('users', {
  id: serial('id').primaryKey(),
  uid: text('uid').notNull().unique(), // Firebase Auth UID or system ID
  tenantId: text('tenant_id').notNull().default('tenant-zakirly-curriculum'),
  name: text('name').notNull(),
  nameAr: text('name_ar'),
  email: text('email').notNull(),
  role: text('role').notNull().default('supervisor'),
  avatar: text('avatar'),
  phone: text('phone'),
  status: text('status').notNull().default('active'),
  linkedEntityId: text('linked_entity_id'),
  lastLogin: text('last_login'),
  createdAt: timestamp('created_at').defaultNow(),
});

export const tenants = pgTable('tenants', {
  id: text('id').primaryKey(),
  nameAr: text('name_ar').notNull(),
  nameEn: text('name_en').notNull(),
  code: text('code').notNull(),
  logo: text('logo'),
  currency: text('currency').notNull().default('SAR'),
  phone: text('phone'),
  email: text('email'),
  status: text('status').notNull().default('active'),
});

export const students = pgTable('students', {
  id: text('id').primaryKey(),
  tenantId: text('tenant_id').notNull(),
  code: text('code').notNull(),
  nameAr: text('name_ar').notNull(),
  nameEn: text('name_en').notNull(),
  gender: text('gender').notNull().default('male'),
  email: text('email'),
  phone: text('phone'),
  parentId: text('parent_id'),
  parentNameAr: text('parent_name_ar'),
  grade: text('grade'),
  status: text('status').notNull().default('active'),
  balance: doublePrecision('balance').notNull().default(0),
  remainingSessions: integer('remaining_sessions').notNull().default(0),
  totalSessionsCompleted: integer('total_sessions_completed').notNull().default(0),
  currency: text('currency').default('SAR'),
  packageId: text('package_id'),
  packageNameAr: text('package_name_ar'),
  enrolledCourseIds: jsonb('enrolled_course_ids').$type<string[]>().default([]),
  enrolledTeachers: jsonb('enrolled_teachers').$type<{ teacherId: string; teacherNameAr: string; subject: string }[]>().default([]),
  assignedTeacherId: text('assigned_teacher_id'),
  assignedTeacherNameAr: text('assigned_teacher_name_ar'),
  notes: text('notes'),
  createdAt: text('created_at').notNull(),
});

export const parents = pgTable('parents', {
  id: text('id').primaryKey(),
  tenantId: text('tenant_id').notNull(),
  code: text('code').notNull(),
  nameAr: text('name_ar').notNull(),
  nameEn: text('name_en').notNull(),
  phone: text('phone'),
  whatsapp: text('whatsapp'),
  email: text('email'),
  occupation: text('occupation'),
  relationship: text('relationship'),
  childrenIds: jsonb('children_ids').$type<string[]>().default([]),
  totalDue: doublePrecision('total_due').notNull().default(0),
  createdAt: text('created_at').notNull(),
});

export const teachers = pgTable('teachers', {
  id: text('id').primaryKey(),
  tenantId: text('tenant_id').notNull(),
  code: text('code').notNull(),
  nameAr: text('name_ar').notNull(),
  nameEn: text('name_en').notNull(),
  email: text('email'),
  phone: text('phone'),
  subjects: jsonb('subjects').$type<string[]>().default([]),
  languages: jsonb('languages').$type<string[]>().default([]),
  hourlyRate: doublePrecision('hourly_rate').notNull().default(0),
  perSessionRate: doublePrecision('per_session_rate').notNull().default(0),
  status: text('status').notNull().default('active'),
  totalEarned: doublePrecision('total_earned').notNull().default(0),
  completedSessionsCount: integer('completed_sessions_count').notNull().default(0),
  rating: doublePrecision('rating').notNull().default(5.0),
  bio: text('bio'),
  joinedDate: text('joined_date').notNull(),
});

export const courseSubjects = pgTable('course_subjects', {
  id: text('id').primaryKey(),
  tenantId: text('tenant_id').notNull(),
  code: text('code').notNull(),
  titleAr: text('title_ar').notNull(),
  titleEn: text('title_en').notNull(),
  category: text('category').notNull().default('general'),
  level: text('level'),
  pricePerSession: doublePrecision('price_per_session').notNull().default(0),
  suggestedDurationMinutes: integer('suggested_duration_minutes').notNull().default(60),
  status: text('status').notNull().default('active'),
  descriptionAr: text('description_ar'),
});

export const packageSubscriptions = pgTable('package_subscriptions', {
  id: text('id').primaryKey(),
  tenantId: text('tenant_id').notNull(),
  studentId: text('student_id').notNull(),
  studentNameAr: text('student_name_ar').notNull(),
  courseId: text('course_id').notNull(),
  courseTitleAr: text('course_title_ar').notNull(),
  totalSessions: integer('total_sessions').notNull().default(0),
  remainingSessions: integer('remaining_sessions').notNull().default(0),
  price: doublePrecision('price').notNull().default(0),
  paidAmount: doublePrecision('paid_amount').notNull().default(0),
  currency: text('currency').default('SAR'),
  startDate: text('start_date').notNull(),
  endDate: text('end_date').notNull(),
  status: text('status').notNull().default('active'),
  autoRenewal: boolean('auto_renewal').notNull().default(false),
  notes: text('notes'),
});

export const scheduledSessions = pgTable('scheduled_sessions', {
  id: text('id').primaryKey(),
  tenantId: text('tenant_id').notNull(),
  code: text('code').notNull(),
  courseId: text('course_id').notNull(),
  subjectNameAr: text('subject_name_ar').notNull(),
  teacherId: text('teacher_id').notNull(),
  teacherNameAr: text('teacher_name_ar').notNull(),
  studentId: text('student_id').notNull(),
  studentNameAr: text('student_name_ar').notNull(),
  date: text('date').notNull(),
  startTime: text('start_time').notNull(),
  endTime: text('end_time').notNull(),
  durationMinutes: integer('duration_minutes').notNull().default(60),
  status: text('status').notNull().default('scheduled'),
  meetingUrl: text('meeting_url'),
  roomName: text('room_name'),
  notes: text('notes'),
  completedAt: text('completed_at'),
  teacherPaid: boolean('teacher_paid').notNull().default(false),
});

export const attendanceRecords = pgTable('attendance_records', {
  id: text('id').primaryKey(),
  tenantId: text('tenant_id').notNull(),
  sessionId: text('session_id').notNull(),
  studentId: text('student_id').notNull(),
  studentNameAr: text('student_name_ar').notNull(),
  teacherId: text('teacher_id').notNull(),
  teacherNameAr: text('teacher_name_ar'),
  date: text('date').notNull(),
  status: text('status').notNull().default('present'),
  minutesLate: integer('minutes_late').default(0),
  notes: text('notes'),
  loggedBy: text('logged_by').notNull(),
  timestamp: text('timestamp').notNull(),
});

export const paymentInvoices = pgTable('payment_invoices', {
  id: text('id').primaryKey(),
  tenantId: text('tenant_id').notNull(),
  invoiceNumber: text('invoice_number').notNull(),
  studentId: text('student_id').notNull(),
  studentNameAr: text('student_name_ar').notNull(),
  parentId: text('parent_id'),
  parentNameAr: text('parent_name_ar'),
  amount: doublePrecision('amount').notNull().default(0),
  paidAmount: doublePrecision('paid_amount').notNull().default(0),
  remainingAmount: doublePrecision('remaining_amount').notNull().default(0),
  currency: text('currency').default('SAR'),
  paymentMethod: text('payment_method'),
  status: text('status').notNull().default('unpaid'),
  type: text('type').notNull().default('subscription'),
  dueDate: text('due_date').notNull(),
  paidDate: text('paid_date'),
  transactionRef: text('transaction_ref'),
  receiptNumber: text('receipt_number'),
  notes: text('notes'),
  createdAt: text('created_at').notNull(),
  subjectNameAr: text('subject_name_ar'),
  teacherId: text('teacher_id'),
  teacherNameAr: text('teacher_name_ar'),
  teacherRate: doublePrecision('teacher_rate'),
  sessionsCount: integer('sessions_count'),
  exchangeRate: doublePrecision('exchange_rate'),
});

export const payrollRecords = pgTable('payroll_records', {
  id: text('id').primaryKey(),
  tenantId: text('tenant_id').notNull(),
  teacherId: text('teacher_id').notNull(),
  teacherNameAr: text('teacher_name_ar').notNull(),
  month: integer('month').notNull(),
  year: integer('year').notNull(),
  sessionsCount: integer('sessions_count').notNull().default(0),
  totalHours: doublePrecision('total_hours').notNull().default(0),
  ratePerSession: doublePrecision('rate_per_session').notNull().default(0),
  grossAmount: doublePrecision('gross_amount').notNull().default(0),
  bonus: doublePrecision('bonus').notNull().default(0),
  deductions: doublePrecision('deductions').notNull().default(0),
  netSalary: doublePrecision('net_salary').notNull().default(0),
  status: text('status').notNull().default('draft'),
  isSettled: boolean('is_settled').default(false),
  settledAt: text('settled_at'),
  paidDate: text('paid_date'),
  notes: text('notes'),
});

export const trialLessons = pgTable('trial_lessons', {
  id: text('id').primaryKey(),
  tenantId: text('tenant_id').notNull(),
  studentNameAr: text('student_name_ar').notNull(),
  parentPhone: text('parent_phone').notNull(),
  parentNameAr: text('parent_name_ar').notNull(),
  courseId: text('course_id').notNull(),
  courseTitleAr: text('course_title_ar').notNull(),
  assignedTeacherId: text('assigned_teacher_id').notNull(),
  assignedTeacherNameAr: text('assigned_teacher_name_ar').notNull(),
  scheduledDate: text('scheduled_date').notNull(),
  scheduledTime: text('scheduled_time').notNull(),
  status: text('status').notNull().default('scheduled'),
  conversionFeedback: text('conversion_feedback'),
  convertedSubscriptionId: text('converted_subscription_id'),
  createdAt: text('created_at').notNull(),
});

export const systemNotifications = pgTable('system_notifications', {
  id: text('id').primaryKey(),
  tenantId: text('tenant_id').notNull(),
  targetRole: text('target_role').default('all'),
  titleAr: text('title_ar').notNull(),
  titleEn: text('title_en').notNull(),
  messageAr: text('message_ar').notNull(),
  messageEn: text('message_en').notNull(),
  type: text('type').notNull().default('info'),
  read: boolean('read').notNull().default(false),
  createdAt: text('created_at').notNull(),
  linkModule: text('link_module'),
});

export const auditLogs = pgTable('audit_logs', {
  id: text('id').primaryKey(),
  tenantId: text('tenant_id').notNull(),
  userName: text('user_name').notNull(),
  userRole: text('user_role').notNull(),
  actionAr: text('action_ar').notNull(),
  actionEn: text('action_en').notNull(),
  module: text('module').notNull(),
  details: text('details').notNull(),
  timestamp: text('timestamp').notNull(),
  ip: text('ip').notNull().default('127.0.0.1'),
});

export const appStateStore = pgTable('app_state_store', {
  key: text('key').primaryKey(),
  value: jsonb('value').notNull(),
  updatedAt: timestamp('updated_at').defaultNow(),
});
